CLASS zcl_lab_18_animal DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk RETURNING VALUE(p_walk) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_18_ANIMAL IMPLEMENTATION.


  METHOD walk.
    p_walk = 'Animal is walking'.
  ENDMETHOD.
ENDCLASS.
