CLASS zcl_lab_23_company DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA capital TYPE string VALUE '100$'..
ENDCLASS.



CLASS zcl_lab_23_company IMPLEMENTATION.
ENDCLASS.
