CLASS zcl_lab_18_animal DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk RETURNING VALUE(p_walk) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_18_animal IMPLEMENTATION.
  METHOD walk.
    p_walk = 'Animal is walking'.
  ENDMETHOD.

ENDCLASS.
