CLASS zcx_lab_57_format_unknown DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_LAB_57_FORMAT_UNKNOWN IMPLEMENTATION.
ENDCLASS.
