CLASS zcl_lab_39_budget DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_budget ABSTRACT RETURNING VALUE(rv_budget)  TYPE string,
             set_budget ABSTRACT IMPORTING iv_budget TYPE string.
  PROTECTED SECTION.
    DATA budget TYPE string.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_lab_39_budget IMPLEMENTATION.

ENDCLASS.
