CLASS zcl_lab_33_expatriate_empl DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES zif_lab_04_employee .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_33_EXPATRIATE_EMPL IMPLEMENTATION.


  METHOD zif_lab_04_employee~get_employees_count.
    rv_count = 10.
  ENDMETHOD.
ENDCLASS.
